### ISSUE TITLE
你好，我是在学习武sir的Django框架的一名程序员，看你也应该是在看他的课程，遇到个Bug，调了一周了，没有什么进展，在github上搜了下仓库的名称，

### ISSUE THREAD

**Issue by linjiesen** [yeguoku/s25#2]
你也应该是在看他的课程，遇到个Bug，调了一周了，没有什么进展，在github上搜了下仓库的名称，有幸搜到了你的repo，Bug是在P86,使用中间件实现登录的时候在PricePolicy表中同时也插入一条数据，代码和武sir代码是一样的，环境配置也是一样的，如果您也遇到这个问题或者知道这个问题怎么解决，希望能和你进行更深入的交流，谢谢～
Traceback (most recent call last):
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alroy/Program/Django/s25/web/views/account.py", line 43, in register
    start_datetime=datetime.datetime.now()
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/alroy/anaconda3/envs/Django1_py36/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: web_transaction.price_policy_id
[14/Jul/2020 12:44:04] "POST /register/ HTTP/1.1" 500 19402

**Comment by linjiesen** [comment]
之前课程中的离线脚本没有执行导致这个错误，执行那个脚本在数据库中创建了数据就不会有这个错误了
